# Generated by Django 4.1.5 on 2023-01-30 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.CharField(max_length=10)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('latitude', models.IntegerField(blank=True, default=None)),
                ('longitude', models.IntegerField(blank=True, default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Itens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agua', models.IntegerField(blank=True, default=None)),
                ('alimento', models.IntegerField(blank=True, default=None)),
                ('medicamento', models.IntegerField(blank=True, default=None)),
                ('municao', models.IntegerField(blank=True, default=None)),
            ],
        ),
    ]
