# Generated by Django 4.1.5 on 2023-01-30 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastrar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itens',
            name='agua',
        ),
        migrations.RemoveField(
            model_name='itens',
            name='alimento',
        ),
        migrations.RemoveField(
            model_name='itens',
            name='medicamento',
        ),
        migrations.RemoveField(
            model_name='itens',
            name='municao',
        ),
    ]
