# Generated by Django 4.1.5 on 2023-01-30 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastrar', '0002_remove_itens_agua_remove_itens_alimento_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Itens',
            new_name='Agua',
        ),
    ]
