# Generated by Django 4.1.5 on 2023-01-30 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastrar', '0003_rename_itens_agua'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agua',
        ),
    ]
